/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/common/Header.vue')['default']
    HorseList: typeof import('./src/components/race/HorseList.vue')['default']
    IconMdiCheck: typeof import('~icons/mdi/check')['default']
    IconMdiFlagCheckered: typeof import('~icons/mdi/flag-checkered')['default']
    IconMdiHorse: typeof import('~icons/mdi/horse')['default']
    IconMdiHorseVariantFast: typeof import('~icons/mdi/horse-variant-fast')['default']
    IconMdiHourglass: typeof import('~icons/mdi/hourglass')['default']
    IconMdiNoteTextOutline: typeof import('~icons/mdi/note-text-outline')['default']
    IconMdiTrophy: typeof import('~icons/mdi/trophy')['default']
    InfoBox: typeof import('./src/components/common/InfoBox.vue')['default']
    RaceProgramAndResults: typeof import('./src/components/race/RaceProgramAndResults.vue')['default']
    RaceResults: typeof import('./src/components/race/RaceResults.vue')['default']
    RaceTrack: typeof import('./src/components/race/RaceTrack.vue')['default']
    RoundItem: typeof import('./src/components/race/RoundItem.vue')['default']
    RoundList: typeof import('./src/components/race/RoundList.vue')['default']
  }
}
